# Site settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

title: ChiPy Algorithms SIG
email: chicago-sig-organizers@python.org
description: >- # this means to ignore newlines until "baseurl:"
  Algo SIG is a Chicago Python special interest group where we discuss and practice all things algorithms.
baseurl: "/algosig" # the subpath of your site, e.g. /blog
url: "http://chicagopython.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ChicagoPython
github_username:  chicagopython

# Build settings
plugins:
  - jekyll-feed

header_pages:
  - name: About
    path: about.md
    icon: fa fa-info-circle
  - name: Contribute
    path: contribute.md
    icon: fa fa-code-fork
  - name: Connect
    icon: fa fa-users
    dropdown:
      - name: GitHub
        link: https://github.com/chicagopython
        icon: fa fa-github
      - name: Twitter
        link: https://twitter.com/ChicagoPython
        icon: fa fa-twitter
      - name: Slack
        link: https://joinchipyslack.herokuapp.com/
        icon: fa fa-slack
      - name: Email
        link: mailto:chicago-sig-organizers@python.org
        icon: fa fa-envelope

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
